# Copyright (c) 2026 DataXID Teknoloji ve Ticaret A.Ş.
# SPDX-License-Identifier: Apache-2.0
"""
ModelConfig — typed training configuration for Model.create().

Replaces the untyped config dict with IDE-discoverable, validated fields.
Plain dicts are accepted for backwards-compatible ergonomics; see
:func:`_resolve_config` for the normalization rules.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Literal

RareStrategy = Literal["mask", "sample"]


@dataclass(frozen=True)
class Synthetic:
    """
    Generation-time tuning preset for :meth:`Model.generate`.

    Bundles scalar hyperparameters that control *how* synthetic rows are
    produced. Structured constraints (bias-correction, distribution
    override) are passed as separate arguments to :meth:`Model.generate`
    and are intentionally **not** fields of this class — they are
    orthogonal concepts.

    Example::

        from dataxid import Synthetic

        preset = Synthetic(diversity=0.8, rare_cutoff=0.95, seed=42)
        df = model.generate(synthetic=preset, n=1000)

    Override rule:
        When passed via ``Model.generate(synthetic=...)``, an explicit
        keyword argument to ``generate`` always wins over the preset's
        field. Fields left at their default values do not override any
        ``generate`` default.

    Args:
        n: Number of rows (flat) / entities (sequential) to generate.
            ``None`` means "use training data size".
        seed: PRNG seed for deterministic generation. ``None`` means
            non-deterministic.
        diversity: Softmax temperature; lower is more peaked / less
            diverse. Must be > 0.
        rare_cutoff: Nucleus-sampling mass cutoff. Must be in ``(0, 1]``.
        rare_strategy: How rare categories are rendered during generation.
            ``None`` means "fall back to ``ModelConfig.privacy.rare_strategy``".

    Raises:
        ValueError: If ``diversity <= 0``, ``rare_cutoff`` is outside
            ``(0, 1]``, or ``n`` is not a positive integer.
    """

    n: int | None = None
    seed: int | None = None
    diversity: float = 1.0
    rare_cutoff: float = 1.0
    rare_strategy: RareStrategy | None = None

    def __post_init__(self) -> None:
        if self.n is not None and (not isinstance(self.n, int) or self.n <= 0):
            raise ValueError(
                f"Synthetic.n must be a positive integer or None, got {self.n!r}"
            )
        if self.diversity <= 0:
            raise ValueError(
                f"Synthetic.diversity must be > 0, got {self.diversity!r}"
            )
        if not (0 < self.rare_cutoff <= 1):
            raise ValueError(
                f"Synthetic.rare_cutoff must be in (0, 1], got {self.rare_cutoff!r}"
            )


@dataclass(frozen=True)
class Bias:
    """
    Bias-correction config for statistical parity across sensitive groups.

    Used with :meth:`Model.generate` to enforce that the predicted
    distribution of ``target`` is independent of the group membership
    defined by ``sensitive`` columns. Sequential models are not supported.

    Example::

        from dataxid import Bias

        bias = Bias(
            target="income",
            sensitive=["gender", "race"],
        )

    Args:
        target: Name of the target (outcome) column. Must be a non-empty
            string and a categorical column in the training data.
        sensitive: Protected-attribute columns. Must be a non-empty list
            of categorical column names, and must not include ``target``.

    Raises:
        ValueError: If ``target`` is empty / not a string, ``sensitive``
            is empty, contains non-strings, or includes ``target``.
    """

    target: str
    sensitive: list[str]

    def __post_init__(self) -> None:
        if not isinstance(self.target, str) or not self.target:
            raise ValueError(
                f"Bias.target must be a non-empty string, got {self.target!r}"
            )
        if not self.sensitive:
            raise ValueError("Bias.sensitive must be a non-empty list")
        if any(not isinstance(s, str) or not s for s in self.sensitive):
            raise ValueError(
                "Bias.sensitive entries must be non-empty strings"
            )
        if self.target in self.sensitive:
            raise ValueError(
                f"Bias.target ({self.target!r}) cannot appear in sensitive"
            )


@dataclass(frozen=True)
class Distribution:
    """
    Override the empirical distribution of a single categorical column.

    Used with :meth:`Model.generate` and :func:`synthesize` to force the
    output distribution of one column to match a target probability map.
    All other columns are generated by the model normally.

    Example::

        from dataxid import Distribution

        dist = Distribution(
            column="gender",
            probabilities={"M": 0.7, "F": 0.3},
        )

    Args:
        column: Target column name. Must be a non-empty string.
        probabilities: Category → probability mapping. Must be non-empty
            with non-negative values. Values are normalized downstream;
            they need not sum to exactly 1.0.

    Raises:
        ValueError: If ``column`` is empty / not a string, ``probabilities``
            is empty, or any probability is negative.
    """

    column: str
    probabilities: dict[str, float]

    def __post_init__(self) -> None:
        if not isinstance(self.column, str) or not self.column:
            raise ValueError(
                f"Distribution.column must be a non-empty string, got {self.column!r}"
            )
        if not self.probabilities:
            raise ValueError("Distribution.probabilities must be non-empty")
        if any(p < 0 for p in self.probabilities.values()):
            raise ValueError(
                "Distribution.probabilities must be non-negative"
            )


@dataclass
class Privacy:
    """
    Privacy settings applied at training time.

    Two independent protections:

    * **Rare-category protection** (``protect_rare`` + ``rare_strategy``)
      runs during analysis — infrequent values are hidden from the model
      before it ever sees them.
    * **Embedding noise** (``enabled`` + ``noise``) adds Gaussian
      perturbation to embeddings before they cross the API boundary.

    Example::

        from dataxid import Privacy

        Privacy(
            protect_rare=True,
            rare_strategy="mask",  # keep <protected> sentinel visible
            enabled=False,
            noise=0.1,
        )

    Args:
        protect_rare: When True, rare categorical values are replaced
            with the ``<protected>`` sentinel before the vocabulary is
            built. Disable only when the training data contains no
            sensitive rare values.
        rare_strategy: How the ``<protected>`` sentinel is rendered at
            generation time.
            - ``"mask"`` (default): keep ``<protected>`` literal in the
              output, preserving the training distribution and leaving
              an auditable protection trace.
            - ``"sample"``: replace each ``<protected>`` with a random
              draw from the remaining frequent categories.
        enabled: Toggle for embedding noise. When True, Gaussian noise
            is injected into embeddings before they leave the client.
        noise: Standard deviation of the Gaussian noise injected into
            embeddings when ``enabled`` is True.
    """

    protect_rare: bool = True
    rare_strategy: RareStrategy = "mask"
    enabled: bool = False
    noise: float = 0.1


@dataclass
class ModelConfig:
    """
    Training configuration for Model.create().

    Example::

        import dataxid

        model = dataxid.Model.create(
            data=df,
            config=dataxid.ModelConfig(
                embedding_dim=128,
                model_size="large",
                max_epochs=50,
                privacy=dataxid.Privacy(rare_strategy="mask"),
            ),
        )
    """

    embedding_dim: int = 64
    model_size: Literal["small", "medium", "large"] = "medium"
    batch_size: int = 256
    max_epochs: int = 100
    early_stop_patience: int = 4
    val_split: float = 0.1
    privacy: Privacy = field(default_factory=Privacy)
    encoding_types: dict[str, str] | None = None
    accumulation_steps: int = 1
    learning_rate: float | None = None
    label_smoothing: float = 0.0
    embedding_dropout: float = 0.5
    time_limit_seconds: float = 0.0
    seed: int | None = None
    timeout: float = 14400.0

    def to_dict(self) -> dict:
        """Serialize to a plain dict."""
        data = dict(self.__dict__)
        data["privacy"] = dict(self.privacy.__dict__)
        return data


def _resolve_config(config: dict | ModelConfig | None) -> ModelConfig:
    """Normalize config input → ``ModelConfig`` instance.

    Dict inputs may nest ``privacy`` as a dict; it is promoted to a
    :class:`Privacy` instance. Returning the dataclass (not a plain dict)
    lets downstream code access fields with attribute syntax and keeps
    :class:`Privacy` as a single source of truth.
    """
    if config is None:
        return ModelConfig()
    if isinstance(config, ModelConfig):
        return config
    if isinstance(config, dict):
        data = dict(config)
        privacy = data.get("privacy")
        if isinstance(privacy, dict):
            data["privacy"] = Privacy(**privacy)
        elif privacy is None and "privacy" in data:
            data["privacy"] = Privacy()
        return ModelConfig(**data)
    raise TypeError(
        f"config must be a ModelConfig instance or dict, got {type(config).__name__}"
    )


__all__ = [
    "Bias",
    "Distribution",
    "ModelConfig",
    "Privacy",
    "RareStrategy",
    "Synthetic",
    "_resolve_config",
    "replace",
]
