# Copyright (c) 2026 DataXID Teknoloji ve Ticaret A.Ş.
# SPDX-License-Identifier: Apache-2.0
"""
Dataxid Python SDK.

Privacy-preserving synthetic data generation.
Raw data never leaves your environment — only embeddings cross the API boundary.

Quick start::

    import dataxid
    import pandas as pd

    dataxid.api_key = "dx_test_..."
    df = pd.read_csv("data.csv")

    synthetic = dataxid.synthesize(data=df, n_samples=1000)
"""

from __future__ import annotations

__version__ = "0.3.0"

import pandas as pd

from dataxid._log import disable_logging, enable_logging
from dataxid._log import logger as _logger
from dataxid._log import setup_logging as _setup_logging
from dataxid._table import Table
from dataxid.exceptions import (
    APIError,
    AuthenticationError,
    ConflictError,
    DataxidError,
    InvalidRequestError,
    ModelNotReadyError,
    NotFoundError,
    QuotaExceededError,
    RateLimitError,
    TrainingError,
    TrainingTimeoutError,
)
from dataxid.training._config import (
    Bias,
    Distribution,
    ModelConfig,
    Privacy,
    RareStrategy,
    Synthetic,
)
from dataxid.training._model import Model


class _UnsetType:
    """Sentinel type — marker for "caller did not pass this argument"."""

    _instance: _UnsetType | None = None

    def __new__(cls) -> _UnsetType:
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __repr__(self) -> str:
        return "<UNSET>"

    def __bool__(self) -> bool:
        return False


_UNSET = _UnsetType()

api_key: str | None = None
base_url: str = "https://api.dataxid.com"


_setup_logging()


def synthesize(
    data: pd.DataFrame,
    n_samples: int | _UnsetType = _UNSET,
    config: dict | ModelConfig | None = None,
    api_key: str | None = None,
    base_url: str | None = None,
    parent: pd.DataFrame | None = None,
    parent_encoding_types: dict[str, str] | None = None,
    foreign_key: str | None = None,
    parent_key: str | None = None,
    seed: int | None | _UnsetType = _UNSET,
    synthetic: Synthetic | None = None,
    distribution: Distribution | None = None,
    bias: Bias | None = None,
    conditions: pd.DataFrame | None = None,
    diversity: float | _UnsetType = _UNSET,
    rare_cutoff: float | _UnsetType = _UNSET,
    rare_strategy: RareStrategy | None | _UnsetType = _UNSET,
) -> pd.DataFrame:
    """
    Generate synthetic data in one call.

    This is the simplest way to use Dataxid. Equivalent to::

        model = dataxid.Model.create(data=df, n_samples=n)
        synthetic = model.generate()
        model.delete()

    Raw data never leaves your machine. Only embeddings (64 floats/row)
    are sent to the API.

    Args:
        data: Training DataFrame
        n_samples: Number of synthetic rows to generate. When ``conditions``
            is provided, must be omitted or match ``len(conditions)``.
        config: Training config (model_size, embedding_dim, max_epochs, etc.)
        api_key: Override dataxid.api_key
        base_url: Override dataxid.base_url
        parent: Parent table for context-aware generation (1:1 aligned or joined via foreign_key)
        parent_encoding_types: Encoding overrides for parent columns
        foreign_key: FK column in data linking rows to parent (enables sequential mode)
        parent_key: PK column in parent table (inferred from foreign_key if same name)
        seed: Random seed for reproducible training and generation. None = non-deterministic.
        synthetic: Optional :class:`Synthetic` preset bundling scalar
            generation-time tuning. Explicit keyword arguments always
            override preset fields.
        distribution: Override the empirical distribution of a single
            categorical column. See :class:`Distribution`.
        bias: Bias-correction config for statistical parity across sensitive
            groups. See :class:`Bias`.
        conditions: DataFrame for conditional generation. Columns present in
            conditions are fixed; remaining columns are generated by the model.
        diversity: Sampling diversity. ``1.0`` = model distribution,
            ``<1.0`` = sharper (more deterministic), ``>1.0`` = flatter
            (more diverse). Must be > 0.
        rare_cutoff: Nucleus sampling cutoff in ``(0, 1]``. ``1.0`` disables
            nucleus sampling (uses the full distribution). Lower values
            trim the rare tail of the categorical distribution.
        rare_strategy: How to handle rare (infrequent) categorical values
            during generation. When ``None`` (default), inherits from
            :class:`Privacy` on the training config. Explicit values override.
            - ``"mask"``: Rare values in categorical columns may appear as the
              literal token ``"<protected>"``. Preserves the original
              distribution, including the presence of rare values.
            - ``"sample"``: Suppress the ``"<protected>"`` token entirely.
              Rare slots are filled by sampling from the frequent categories.
              Use when you need clean string values in categorical columns.

    Returns:
        DataFrame with synthetic data (target columns only)

    Raises:
        InvalidRequestError: If any user input fails validation.
            Inherits from :class:`ValueError`.
    """
    if seed is not _UNSET and seed is not None and (
        not isinstance(seed, int) or isinstance(seed, bool)
    ):
        raise InvalidRequestError(
            f"seed must be an integer or None, got {seed!r}",
            param="seed",
        )
    if diversity is not _UNSET and (
        not isinstance(diversity, (int, float))
        or isinstance(diversity, bool)
        or diversity <= 0
    ):
        raise InvalidRequestError(
            f"diversity must be > 0, got {diversity!r}",
            param="diversity",
        )
    if rare_cutoff is not _UNSET and (
        not isinstance(rare_cutoff, (int, float))
        or isinstance(rare_cutoff, bool)
        or not (0 < rare_cutoff <= 1.0)
    ):
        raise InvalidRequestError(
            f"rare_cutoff must be in (0, 1], got {rare_cutoff!r}",
            param="rare_cutoff",
        )
    if (
        rare_strategy is not _UNSET
        and rare_strategy is not None
        and rare_strategy not in ("mask", "sample")
    ):
        raise InvalidRequestError(
            f"rare_strategy must be 'mask', 'sample', or None, "
            f"got {rare_strategy!r}",
            param="rare_strategy",
        )

    n_explicit: int | None = n_samples if n_samples is not _UNSET else None
    if n_explicit is None and synthetic is not None:
        n_explicit = synthetic.n

    seed_explicit = seed if seed is not _UNSET else None
    if seed_explicit is not None:
        if config is None:
            config = {"seed": seed_explicit}
        elif isinstance(config, dict):
            config.setdefault("seed", seed_explicit)
        elif isinstance(config, ModelConfig) and config.seed is None:
            config.seed = seed_explicit

    model = Model.create(
        data=data,
        n_samples=n_explicit,
        config=config,
        api_key=api_key,
        base_url=base_url,
        parent=parent,
        parent_encoding_types=parent_encoding_types,
        foreign_key=foreign_key,
        parent_key=parent_key,
    )
    try:
        gen_kwargs: dict = {
            "synthetic": synthetic,
            "conditions": conditions,
            "distribution": distribution,
            "bias": bias,
        }
        if n_samples is not _UNSET:
            gen_kwargs["n_samples"] = n_samples
        for name, value in (
            ("seed", seed),
            ("diversity", diversity),
            ("rare_cutoff", rare_cutoff),
            ("rare_strategy", rare_strategy),
        ):
            if value is not _UNSET:
                gen_kwargs[name] = value
        return model.generate(**gen_kwargs)
    except Exception:
        _logger.warning(
            "generate() failed — deleting model %s and re-raising.", model.id
        )
        raise
    finally:
        model.delete()


def synthesize_tables(
    tables: dict[str, Table],
    config: dict | ModelConfig | None = None,
    api_key: str | None = None,
    base_url: str | None = None,
    seed: int | None = None,
    synthetic: dict[str, Synthetic] | None = None,
    distribution: dict[str, Distribution] | None = None,
    bias: dict[str, Bias] | None = None,
    conditions: dict[str, pd.DataFrame] | None = None,
    diversity: dict[str, float] | None = None,
    rare_cutoff: dict[str, float] | None = None,
    rare_strategy: dict[str, RareStrategy] | None = None,
) -> dict[str, pd.DataFrame]:
    """
    Synthesize multiple related tables with referential integrity.

    Trains and generates each table in dependency order (parents first).
    Primary keys are excluded from training and auto-assigned after generation.
    Foreign keys in child tables reference the synthetic parent's primary keys.

    Example::

        from dataxid import Table

        accounts = Table(accounts_df, primary_key="account_id")
        transactions = Table(transactions_df,
                             foreign_keys={"account_id": accounts})

        syn = dataxid.synthesize_tables({
            "accounts": accounts,
            "transactions": transactions,
        })
        syn["accounts"]       # synthetic accounts with auto-assigned PK
        syn["transactions"]   # synthetic transactions with valid FK references

    Args:
        tables: Mapping of table name to Table definition.
        config: Training config applied to all tables.
        api_key: Override dataxid.api_key.
        base_url: Override dataxid.base_url.
        seed: Random seed for reproducible training and generation. None = non-deterministic.
        distribution: Per-table distribution override. Keys are table names,
            values are :class:`Distribution` instances.
        conditions: Per-table conditional generation data. Keys are table names,
            values are DataFrames whose columns are fixed during generation.
            For flat (root) tables: one row per output row.
            For sequential (child) tables: long-format with the foreign key
            column (e.g. ``account_id``) identifying which entity each
            condition row belongs to.
        diversity: Per-table sampling diversity. Keys are table names,
            values are floats > 0. Tables not present in the dict use the
            default ``1.0`` (model distribution).
        rare_cutoff: Per-table nucleus sampling cutoff. Keys are table names,
            values are floats in ``(0, 1]``. Tables not present in the dict
            use the default ``1.0`` (nucleus sampling disabled). Lower values
            trim the rare tail of the categorical distribution.
        rare_strategy: Per-table handling of rare categorical values. Keys are
            table names, values are ``"mask"`` or ``"sample"``. Tables not
            present inherit from the training-time ``Privacy.rare_strategy``.
            See :func:`synthesize` for the semantics of each option.

    Returns:
        Dict mapping table name to synthetic DataFrame.

    Raises:
        InvalidRequestError: If any user input fails validation.
            Inherits from :class:`ValueError`.
    """
    if seed is not None and (
        not isinstance(seed, int) or isinstance(seed, bool)
    ):
        raise InvalidRequestError(
            f"seed must be an integer or None, got {seed!r}",
            param="seed",
        )

    if seed is not None:
        if config is None:
            config = {"seed": seed}
        elif isinstance(config, dict):
            config.setdefault("seed", seed)
        elif isinstance(config, ModelConfig) and config.seed is None:
            config.seed = seed

    _validate_per_table_dict(
        diversity, tables, name="diversity",
        validator=_is_positive_number, hint="a number > 0",
    )
    _validate_per_table_dict(
        rare_cutoff, tables, name="rare_cutoff",
        validator=_is_rare_cutoff_number, hint="a number in (0, 1]",
    )
    _validate_per_table_dict(
        rare_strategy, tables, name="rare_strategy",
        validator=lambda v: v in ("mask", "sample"),
        hint="'mask' or 'sample'",
    )
    _validate_per_table_dict(
        synthetic, tables, name="synthetic",
        validator=lambda v: isinstance(v, Synthetic),
        hint="a Synthetic instance",
    )
    _validate_per_table_dict(
        distribution, tables, name="distribution",
        validator=lambda v: isinstance(v, Distribution),
        hint="a Distribution instance",
    )
    _validate_per_table_dict(
        bias, tables, name="bias",
        validator=lambda v: isinstance(v, Bias),
        hint="a Bias instance",
    )
    _validate_per_table_dict(
        conditions, tables, name="conditions",
        validator=lambda v: isinstance(v, pd.DataFrame),
        hint="a pandas DataFrame",
    )

    from dataxid._table import (
        _assign_primary_keys,
        _remap_foreign_keys,
        _resolve_fk_targets,
        _topological_sort,
        _validate_tables,
    )

    _validate_tables(tables)
    order = _topological_sort(tables)
    assert order is not None  # _validate_tables guarantees no cycles
    fk_targets = _resolve_fk_targets(tables)

    results: dict[str, pd.DataFrame] = {}

    for name in order:
        tbl = tables[name]
        pk_col = tbl.primary_key
        resolved_fks = fk_targets[name]

        training_data = tbl.data
        if pk_col is not None:
            training_data = training_data.drop(columns=[pk_col])

        tbl_synthetic = (synthetic or {}).get(name)
        tbl_dist = (distribution or {}).get(name)
        tbl_bias = (bias or {}).get(name)
        tbl_conditions = (conditions or {}).get(name)
        tbl_diversity = (diversity or {}).get(name, 1.0)
        tbl_rare_cutoff = (rare_cutoff or {}).get(name, 1.0)
        tbl_rare_strategy = (rare_strategy or {}).get(name)

        ctx_fk = _pick_context_fk(tbl)
        if ctx_fk:
            parent_name = resolved_fks[ctx_fk]
            parent_tbl = tables[parent_name]
            parent_syn = results[parent_name]

            real_parent = parent_tbl.data
            model = Model.create(
                data=training_data,
                config=config,
                api_key=api_key,
                base_url=base_url,
                parent=real_parent,
                parent_key=parent_tbl.primary_key,
                foreign_key=ctx_fk,
            )
            try:
                syn_df = model.generate(
                    synthetic=tbl_synthetic,
                    parent=parent_syn, conditions=tbl_conditions,
                    seed=seed, distribution=tbl_dist, bias=tbl_bias,
                    diversity=tbl_diversity, rare_cutoff=tbl_rare_cutoff,
                    rare_strategy=tbl_rare_strategy,
                )
            except Exception:
                _logger.warning(
                    "generate() failed for table '%s' — deleting model %s and re-raising.",
                    name, model.id,
                )
                raise
            finally:
                model.delete()
        else:
            n = len(tbl_conditions) if tbl_conditions is not None else len(tbl.data)
            syn_kwargs: dict = {
                "data": training_data,
                "n_samples": n,
                "config": config,
                "api_key": api_key,
                "base_url": base_url,
                "synthetic": tbl_synthetic,
                "distribution": tbl_dist,
                "bias": tbl_bias,
                "conditions": tbl_conditions,
            }
            if seed is not None:
                syn_kwargs["seed"] = seed
            if (diversity or {}).get(name) is not None:
                syn_kwargs["diversity"] = tbl_diversity
            if (rare_cutoff or {}).get(name) is not None:
                syn_kwargs["rare_cutoff"] = tbl_rare_cutoff
            if tbl_rare_strategy is not None:
                syn_kwargs["rare_strategy"] = tbl_rare_strategy
            syn_df = synthesize(**syn_kwargs)

        for fk_c, par_name in resolved_fks.items():
            if fk_c == ctx_fk:
                continue
            par_syn = results[par_name]
            par_pk = tables[par_name].primary_key
            if par_pk is not None:
                syn_df = _remap_foreign_keys(syn_df, fk_c, par_syn, par_pk)

        if pk_col is not None:
            syn_df = _assign_primary_keys(syn_df, pk_col, tbl.pk_type)

        results[name] = syn_df

    return results


def _validate_per_table_dict(
    value: dict | None,
    tables: dict[str, Table],
    *,
    name: str,
    validator,
    hint: str,
) -> None:
    """Fail fast on bad per-table params before any model is trained."""
    if value is None:
        return
    unknown = set(value) - set(tables)
    if unknown:
        raise InvalidRequestError(
            f"{name} refers to unknown table(s): {sorted(unknown)}. "
            f"Known tables: {sorted(tables)}",
            param=name,
        )
    for tbl_name, v in value.items():
        if not validator(v):
            raise InvalidRequestError(
                f"{name}[{tbl_name!r}] must be {hint}, got {v!r}",
                param=name,
            )


def _is_positive_number(v) -> bool:
    return isinstance(v, (int, float)) and not isinstance(v, bool) and v > 0


def _is_rare_cutoff_number(v) -> bool:
    return isinstance(v, (int, float)) and not isinstance(v, bool) and 0 < v <= 1.0


def _pick_context_fk(tbl: Table) -> str | None:
    """Determine which FK column to use as sequential context.

    Returns None if the table has no foreign_keys or sequential=False.
    For single FK → that FK. For multiple FKs → sequence_by (validated by Table).
    """
    if not tbl.foreign_keys or not tbl.sequential:
        return None
    if tbl.sequence_by:
        return tbl.sequence_by
    if len(tbl.foreign_keys) == 1:
        return next(iter(tbl.foreign_keys))
    return None


__all__ = [
    "enable_logging",
    "disable_logging",
    "api_key",
    "base_url",
    "synthesize",
    "synthesize_tables",
    "Table",
    "Model",
    "ModelConfig",
    "Bias",
    "Distribution",
    "Privacy",
    "RareStrategy",
    "Synthetic",
    "DataxidError",
    "AuthenticationError",
    "InvalidRequestError",
    "ModelNotReadyError",
    "NotFoundError",
    "RateLimitError",
    "QuotaExceededError",
    "ConflictError",
    "TrainingError",
    "TrainingTimeoutError",
    "APIError",
]
